apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: rodrigordavila/strapi-k8s:latest
        ports:
          - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  selector:
    app: strapi
  ports:
  - port: 80
    targetPort: 1337
  type: LoadBalancer